# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: $(TeamProject)_$(BuildID)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd).$(Rev:.r)

# A trigger specifies what branches will cause a continuous integration build to run. 
trigger:
- master

# A pull request trigger specifies what branches will cause a pull request build to run. 
pr:
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md
    - .gitignore
    - .gitmodules

pool:
  vmImage: 'Ubuntu-16.04'

steps:
  - script: cmake .
    displayName: 'Herbertcat build $(BuildID)'
  - script: ls -1 $AGENT_WORKFOLDER
    displayName: 'UnitTesting build $(BuildID)'


