//
// Created by Max on 30.04.2019.
//

#ifndef P3AT_HERBERT_IVIRTUALDEVICEMANAGER_H
#define P3AT_HERBERT_IVIRTUALDEVICEMANAGER_H


class IVirtualDeviceManager {

};


#endif //P3AT_HERBERT_IVIRTUALDEVICEMANAGER_H
